# In this file, you can add more tests to run either by adding a new step or
# adding a new command to an existing step. See different options here for examples.
# This script will be feed into Jinja template in `test-template.j2` to generate
# the final pipeline yaml file.

steps:
- label: Dummy Test
  command: ls 
"""
We remove conventional CI steps to test AMD CI, that runs in the container at .buildkite/run-amd-test.sh 
"""
